# Generated by Django 6.0.6 on 2026-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/'),
        ),
    ]
